史莱姆:
  suffix: ["-小怪.jpeg", "-收益.jpeg"]
  des: []
  alias: ["史莱姆"]
弓萨:
  suffix: ["a.jpeg"]
  des: []
  alias: ["弓萨", "弓萨a", "萨满"]
镜讨萤:
  suffix: [".jpg"]
  des: []
  alias: ["镜讨萤", "jty"]

苦种:
  suffix: [".jpeg"]
  des: []
  alias: ["苦种"]
枯叶紫英:
  suffix: []
  des: "枯叶紫英7分钟70个\nb站视频号：BV1ELSTYSEi1"
  alias: ["枯叶紫英"]
青蜜莓:
  suffix: [".png"]
  des: "两分半66+18个青蜜莓\nb站视频号：BV19cBFYdEBJ"
  alias: ["青蜜莓"]